import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        {/* Global header/navigation */}
        <header className="p-4 bg-white shadow flex justify-between items-center">
          <Link href="/" className="transition transform duration-300 hover:scale-105">
            <button className="focus:outline-none">
              <Image
                src="/ordex.png"
                alt="ordex logo"
                width={180}
                height={38}
                priority
              />
            </button>
          </Link>
          <nav className="flex gap-4">
            <Link 
              href="/" 
              className="transition transform duration-300 hover:scale-105"
            >
              Home
            </Link>
            <Link 
              href="/signIn" 
              className="transition transform duration-300 hover:scale-105"
            >
              Sign In
            </Link>
            <Link 
              href="/orders" 
              className="transition transform duration-300 hover:scale-105"
            >
              All Orders
            </Link>
            <Link
             href="/place"
             className="transition transform duration-300 hover:scale-105"
             >
            Place Pallet
            </Link>
            <Link 
              href="/newOrder" 
              className="transition transform duration-300 hover:scale-105"
            >
              New Order
            </Link>
          </nav>
        </header>
        
        {/* Main content — each route’s page */}
        <main className="flex-1 flex flex-col items-center justify-center p-4">
          {children}
        </main>

        {/* Global footer */}
        <footer className="p-4 bg-white text-center">
          <small>&copy; OrderX</small>
        </footer>
      </body>
    </html>
  );
}
